name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator libsdl2-dev libsdl2-ttf-dev build-essential
    - name: Build simulator
      run: make
      working-directory: sim
    - name: Build blitter smoke test
      run: make blit-smoketest
    - name: Build libhydra helper
      run: make libhydra
    - name: Try building Linux drivers (optional)
      run: |
        sudo apt-get install -y linux-headers-$(uname -r)
        make -C /lib/modules/$(uname -r)/build M=$PWD/drivers/linux modules
      continue-on-error: true
    - name: Build blitter smoke test
      run: make blit-smoketest
      working-directory: .
